[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project]
name = "rksfunc"
version = "1.1.4"
readme = "readme.md"
license-files = ["LICENSES.md", "LICENSES/*.txt"]
dependencies = []

[project.urls]
Source = "https://github.com/RyougiKukoc/rksfunc"

[tool.hatch.build.targets.wheel]
packages = ["rksfunc"]

[tool.hatch.build.targets.sdist]
include = ["/rksfunc", "/pyproject.toml", "/readme.md", "/LICENSES.md", "/LICENSES"]
